title:            klundberg.com
description:      Kevin Lundberg's Blog
url:              http://klundberg.com
locale:           en
reading_time:     true
words_per_minute: 200

permalink:   /blog/:title

gems: [jekyll-paginate]

# Amount of post to show on home page
paginate: 12

defaults:
  -
    scope:
      path: ""
    values:
      comments: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      hidden: false
      image:
        feature:       abstract-4.jpg
        credit:        dargadgetz
        creditlink:    http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/
        show_in_index: false

# Owner/author information
owner:
  name:           Kevin Lundberg
  avatar:         avatar.jpg
  bio:            "I'm a software developer, currently working on iOS applications at Wayfair.com. My views and words are my own."
  email:          kevin@klundberg.com
  twitter:        kevlario
  github:         klundberg
  stackexchange:  https://stackexchange.com/users/10244/kevlar
  linkedin:
  onename:        kevlario

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-61806406-1
google_verify:    dm22KL26h3zCTvGyJcB3A0iQ26RnQ_VoErd22Usa94E
bing_verify:      DD03480E534E01CB8767C5D9E73FD4DC

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true

highlighter: pygments
markdown:    kramdown

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
