title:            klundberg.com
description:      My home on the internets.
# reading_time:     true
# words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              http://www.klundberg.com

defaults:
  -
    scope:
      path: ""
    values:
      comments: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Kevin Lundberg
      hidden: false
      image:
        feature:       abstract-4.jpg
        credit:        dargadgetz
        creditlink:    http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/
        show_in_index: false

# Owner/author information
owner:
  name:           Kevin Lundberg
  avatar:         avatar.jpg
  bio:            "I'm a mobile software developer, working on iOS applications at Wayfair."
  email:          kevin@klundberg.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        kevlario
  github:         klundberg
  stackexchange:  https://stackexchange.com/users/10244/kevlar
  linkedin:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:    dm22KL26h3zCTvGyJcB3A0iQ26RnQ_VoErd22Usa94E
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:      DD03480E534E01CB8767C5D9E73FD4DC

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /blog/:title

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
